stages:
    - deploy

gitlab-pages:
    when: manual
    stage: deploy
    script:
        - mkdir -p public
        - echo '<!DOCTYPE html><html><body><img src="report.png"></body></html>' > public/index.html
    pages: true
